CREATE TABLE IF NOT EXISTS public.company
(
    recruiter_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    recruiter_name character varying COLLATE pg_catalog."default" NOT NULL,
    recruiter_email character varying COLLATE pg_catalog."default" NOT NULL,
    recruiter_phone character varying COLLATE pg_catalog."default" NOT NULL,
    recruiter_password character varying COLLATE pg_catalog."default" NOT NULL,
    recruiter_photo character varying COLLATE pg_catalog."default",
    recruiter_position character varying COLLATE pg_catalog."default" NOT NULL,
    company_name character varying COLLATE pg_catalog."default",
    business_fields character varying COLLATE pg_catalog."default",
    company_city character varying COLLATE pg_catalog."default",
    company_description text COLLATE pg_catalog."default",
    company_instagram character varying COLLATE pg_catalog."default",
    company_linkedin character varying COLLATE pg_catalog."default",
    CONSTRAINT company_pkey PRIMARY KEY (recruiter_id)
)

CREATE TABLE IF NOT EXISTS public.detailuser
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer,
    job_title character varying(50) COLLATE pg_catalog."default",
    address character varying(50) COLLATE pg_catalog."default",
    job_type character varying(50) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    tempat_kerja character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT detailuser_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.hire
(
    hire_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    hire_message character varying COLLATE pg_catalog."default",
    hire_name character varying COLLATE pg_catalog."default",
    hire_email character varying COLLATE pg_catalog."default",
    hire_phone integer,
    hire_description text COLLATE pg_catalog."default",
    id integer,
    recruiter_id integer,
    CONSTRAINT hire_pkey PRIMARY KEY (hire_id),
    CONSTRAINT hire_id_fkey FOREIGN KEY (id)
        REFERENCES public.registeruser (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT hire_recruiter_id_fkey FOREIGN KEY (recruiter_id)
        REFERENCES public.company (recruiter_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public."jobDetailUser"
(
    id integer NOT NULL,
    id_user integer NOT NULL,
    job_title character varying(50) COLLATE pg_catalog."default",
    address character varying(50) COLLATE pg_catalog."default",
    job_type character varying(50) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "jobDetailUser_pkey" PRIMARY KEY (id_user)
)

CREATE TABLE IF NOT EXISTS public."jobExperience"
(
    id integer NOT NULL,
    id_user integer NOT NULL,
    job_title character varying(50) COLLATE pg_catalog."default",
    company_name character varying(50) COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "jobExperience_pkey" PRIMARY KEY (id_user)
)

CREATE TABLE IF NOT EXISTS public.jobexperience
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer,
    job_title character varying(50) COLLATE pg_catalog."default",
    company_name character varying(50) COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT jobexperience_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.portofolio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer,
    aplication_title character varying(50) COLLATE pg_catalog."default",
    link_repository character varying(100) COLLATE pg_catalog."default",
    portofolio_type character varying(20) COLLATE pg_catalog."default",
    image character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT portofolio_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public."registerUser"
(
    id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    password character varying(100) COLLATE pg_catalog."default",
    user_photo character varying(100) COLLATE pg_catalog."default",
    role character varying(10) COLLATE pg_catalog."default",
    is_hired boolean
)

CREATE TABLE IF NOT EXISTS public.registeruser
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    password character varying(100) COLLATE pg_catalog."default",
    user_photo character varying(100) COLLATE pg_catalog."default" DEFAULT 'https://portal.stkippgri-lubuklinggau.ac.id/index.php/getfile/profileimage/0/0220108901'::character varying,
    role character varying(10) COLLATE pg_catalog."default" DEFAULT 'user'::character varying,
    is_hired boolean DEFAULT false,
    phone_number character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "registerUser_pkey" PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.skill
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer,
    skill character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT skill_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public."socialMedia"
(
    id integer NOT NULL,
    id_user integer NOT NULL,
    instagram character varying(50) COLLATE pg_catalog."default",
    github character varying(50) COLLATE pg_catalog."default",
    gitlab character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "socialMedia_pkey" PRIMARY KEY (id_user)
)

CREATE TABLE IF NOT EXISTS public.socialmedia
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer,
    instagram character varying(50) COLLATE pg_catalog."default",
    github character varying(50) COLLATE pg_catalog."default",
    gitlab character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT socialmedia_pkey PRIMARY KEY (id)
)